apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmi-yolo-client
  namespace: hmi-yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hmi-yolo-client
  template:
    metadata:
      labels:
        app: hmi-yolo-client
    spec:
      containers:
      - name: frontend
        image: hmasidza/hmi-yolo-client:v1.0.1
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://backend-service:5000"
        - name: NODE_ENV
          value: "production"
        command: ["/bin/sh"]
        args: ["-c", "npm run build && npx serve -s build -l 3000"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: hmi-yolo
spec:
  selector:
    app: hmi-yolo-client
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer